name: Say Hello World

on:
  issues:
    types:
      - opened

jobs:
  sayHelloWorld:
    runs-on: ubuntu-latest
    steps:
      # Harden Runner
      - name: Harden Runner # Audit all outbound calls
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          egress-policy: audit

      # Checkout
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      # # Setup Node
      # - name: Setup Node
      #   uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      #   with:
      #     node-version: lts/*

      # # Clean Install
      # - name: Clean Install
      #   run: npm ci

      # Probot Action
      - name: Probot Action
        uses: mnrendra/probot-action@73dc02c4f610eefab7e16c0085b1297d98616d0f
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
